# Generated by Django 4.1.3 on 2022-11-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='events', through='levelupapi.EventGamer', to='levelupapi.gamer'),
        ),
    ]
